name: Docker Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4.0.0
      - name: Generate Matrix
        id: generate-matrix
        run: |
          echo "::set-env name=VERSION::[$(pip index versions markata | grep "Available versions:" | sed "s/Available versions://")]"

  build:
    runs-on: ubuntu-latest
    needs: 
      - generate_matrix
    strategy:
      matrix:
        version: ${{ needs.generate_versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: test
        run: |
          echo ${{ matrix.version }}
