name: Docker Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      VERSIONS: ${{ steps.generate-matrix.env.VERSIONS }}
    steps:
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: '3.10'
      - name: Generate Matrix
        id: generate-matrix
        run: |
          echo "VERSIONS=[$(pip index versions markata | grep "Available versions:" | sed "s/Available versions://")]" >> $GITHUB_ENV
  build:
    runs-on: ubuntu-latest
    needs: 
      - generate_matrix
    strategy:
      matrix:
        version: ${{ needs.generate-matrix.outputs.VERSIONS }}
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: test
        run: |
          echo ${{ matrix.version }}
